version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
